services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask initdb
    startCommand: python app.py
    envVars:
      - key: FLASK_APP
        value: app.py
